# This file was generated by GoReleaser. DO NOT EDIT.
cask "yapi" do
  name "yapi"
  desc "CLI-first, offline-first, git-friendly API client for HTTP, gRPC, and TCP"
  homepage "https://github.com/jamierpond/yapi"
  version "0.3.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yapi"

  on_macos do
    on_intel do
      url "https://github.com/jamierpond/yapi/releases/download/v#{version}/yapi_darwin_amd64.tar.gz"
      sha256 "03a70589c1517636d1d5ac8bcf10b3cfb1a80b620ccb97efdff280f533219f96"
    end
    on_arm do
      url "https://github.com/jamierpond/yapi/releases/download/v#{version}/yapi_darwin_arm64.tar.gz"
      sha256 "67674b5ca35f938c6df850a910fcc4a0f7eb9eb78a479cc8dcf2db8d8f24c944"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jamierpond/yapi/releases/download/v#{version}/yapi_linux_amd64.tar.gz"
      sha256 "69d97276ee5ca7a4d9c37e7ab992f686d1a84c5e5a2097a610c59c519fba6cdd"
    end
    on_arm do
      url "https://github.com/jamierpond/yapi/releases/download/v#{version}/yapi_linux_arm64.tar.gz"
      sha256 "ad1e6df90e6f3de12e1b5b4e810eb4d7f7768615fb43ae13a37fa771e5b5f556"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yapi"]
  end

  caveats do
    "yapi is a CLI tool. After installation, run:"
    "  yapi"
    "For more information: https://github.com/jamierpond/yapi"
  end

  # No zap stanza required
end
