# This file was generated by GoReleaser. DO NOT EDIT.
cask "yapi" do
  name "yapi"
  desc "CLI-first, offline-first, git-friendly API client for HTTP, gRPC, and TCP"
  homepage "https://github.com/jamierpond/yapi"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yapi"

  on_macos do
    on_intel do
      url "https://github.com/jamierpond/yapi/releases/download/v#{version}/yapi_darwin_amd64.tar.gz"
      sha256 "b051b1e2f10ce40235cb10e641dc34c2ceb7d2b5f3cb8fc28f08ff46c89d5f1c"
    end
    on_arm do
      url "https://github.com/jamierpond/yapi/releases/download/v#{version}/yapi_darwin_arm64.tar.gz"
      sha256 "7098e0c1a1bec12b9c5871243144444645afad5d23b49de2d0e0df0a5d21059b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jamierpond/yapi/releases/download/v#{version}/yapi_linux_amd64.tar.gz"
      sha256 "ce35f4e619619a133997e7a31d75f7c0a8395e308c849d2e1ef4633ea5d29c08"
    end
    on_arm do
      url "https://github.com/jamierpond/yapi/releases/download/v#{version}/yapi_linux_arm64.tar.gz"
      sha256 "36fa14034c433ae50bd517cc0e9f78ee2ea6d3837d5fdf4036f115c033058268"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yapi"]
  end

  caveats do
    "yapi is a CLI tool. After installation, run:"
    "  yapi"
    "For more information: https://github.com/jamierpond/yapi"
  end

  # No zap stanza required
end
