# This file was generated by GoReleaser. DO NOT EDIT.
cask "yapi" do
  name "yapi"
  desc "CLI-first, offline-first, git-friendly API client for HTTP, gRPC, and TCP"
  homepage "https://github.com/jamierpond/yapi"
  version "0.6.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yapi"

  on_macos do
    on_intel do
      url "https://github.com/jamierpond/yapi/releases/download/v#{version}/yapi_darwin_amd64.tar.gz"
      sha256 "bc24bbc70b4929d33c4a0a0a72428e49ce90dc46b053350457c066dfe19f4ab0"
    end
    on_arm do
      url "https://github.com/jamierpond/yapi/releases/download/v#{version}/yapi_darwin_arm64.tar.gz"
      sha256 "28bc1b8446bea7d20391491d4469ebd8907d73d79fac215191ba84ffd47a52f0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jamierpond/yapi/releases/download/v#{version}/yapi_linux_amd64.tar.gz"
      sha256 "b7eb768d88ed7867e5843ba09c63841920390e6185131c6acac30a37d8aed2cc"
    end
    on_arm do
      url "https://github.com/jamierpond/yapi/releases/download/v#{version}/yapi_linux_arm64.tar.gz"
      sha256 "a6652494d642aa54e7b1027d6c353971ee749badf7ea11a5e7f9cc5548657332"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yapi"]
  end

  caveats do
    "yapi is a CLI tool. After installation, run:"
    "  yapi"
    "For more information: https://github.com/jamierpond/yapi"
  end

  # No zap stanza required
end
